# Inicializar el kernel (esto debe ir primero)
 /run/initialize

# Configurar la fuente de partículas
 /gun/particle triton
 /gun/energy 1 GeV
 /gun/position 0 0 -10 cm
 /gun/direction 0 0 1

# Especificar número de partículas por evento
 /gun/number 5

# Ver lista de motores gráficos disponibles
 /vis/list

# Usar un motor gráfico disponible (OpenGL si está en tu sistema)
 /vis/open

# Seleccionar el visor y ajustar la vista
 /vis/viewer/select viewer-0
 /vis/viewer/set/viewpointThetaPhi 90 180


# Dibujar el volumen y habilitar visualización
 /vis/drawVolume
 /vis/enable
 /vis/viewer/flush


 # Habilitar la visualización de trayectorias
 /vis/scene/add/trajectories
 /vis/modeling/trajectories/create/drawByCharge




# Ejecutar eventos de simulación
 /run/beamOn 100